import { ChainId } from "types/blockchain";
import { EthereumNetwork, NetworkSlugs } from "./AppEnums";

export interface AppNetworkParams {
    name: string,
    symbol: string,
    chainId: ChainId,
    networkImage: string,
    coinImage: string,
    coinName: string,
    coinSymbol: string,
    decimals: number,
    rpcURL: string,
    explorerURL: string,
    bitqueryNetworkId: string,
    wrappedAddress: string,
    supportSwap: boolean,
    supportPageExplorer: boolean,
    coingeckoId: string,
    usesBitquery: boolean,
    isEvm: boolean,
    supportMagic: boolean,
}


export const AppNetworks: { [slugs in NetworkSlugs]?: AppNetworkParams } = {
    [NetworkSlugs.ethereum]: {
        name: 'Ethereum',
        symbol: 'ETH',
        chainId: ChainId.Mainnet,
        networkImage: '/images/networks/eth_logo.png',
        coinName: 'Ethereum',
        coinImage: '/assets/images/eth_logo.png',
        coinSymbol: 'Eth',
        decimals: 18,
        rpcURL: '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2',
        explorerURL: 'https://etherscan.io',
        bitqueryNetworkId: EthereumNetwork.ethereum,
        wrappedAddress: '',
        usesBitquery: true,
        supportSwap: true,
        supportMagic: true,
        supportPageExplorer: true,
        coingeckoId: 'ethereum',
        isEvm: true,
    },
    [NetworkSlugs.bsc]: {
        name: 'Binance Smart Chain',
        symbol: 'BSC',
        chainId: ChainId.Binance,
        networkImage: '/images/networks/binance-coin-bnb-logo.svg',
        coinName: 'Binance',
        coinImage: '/images/networks/binance-coin-bnb-logo.svg',
        coinSymbol: 'BNB',
        decimals: 18,
        rpcURL: 'https://bsc-dataseed.binance.org/',
        explorerURL: 'https://bscscan.com',
        bitqueryNetworkId: EthereumNetwork.bsc,
        wrappedAddress: '0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c',
        supportSwap: true,
        usesBitquery: true,
        supportMagic: true,
        supportPageExplorer: true,
        coingeckoId: 'binancecoin',
        isEvm: true,
    },
    [NetworkSlugs.matic]: {
        name: 'Polygon',
        symbol: 'Matic',
        chainId: ChainId.Matic,
        networkImage: '/images/networks/polygon-matic-logo.svg',
        coinName: 'Polygon',
        coinImage: '/images/networks/polygon-matic-logo.svg',
        coinSymbol: 'MATIC',
        decimals: 18,
        rpcURL: 'https://polygon-rpc.com/',
        explorerURL: 'https://polygonscan.com',
        bitqueryNetworkId: EthereumNetwork.matic,
        wrappedAddress: '0x0d500B1d8E8eF31E21C99d1Db9A6444d3ADf1270',
        supportSwap: true,
        usesBitquery: true,
        supportMagic: true,
        supportPageExplorer: true,
        coingeckoId: 'matic-network',
        isEvm: true,
    },
    [NetworkSlugs.avalanche]: {
        name: 'Avalanche',
        symbol: 'AVAX',
        chainId: ChainId.Avalanche,
        networkImage: '/images/networks/avalanche.svg',
        coinName: 'Avalanche',
        coinImage: '/images/networks/avalanche.svg',
        coinSymbol: 'AVAX',
        decimals: 18,
        rpcURL: 'https://api.avax.network/ext/bc/C/rpc',
        explorerURL: 'https://snowtrace.io',
        bitqueryNetworkId: EthereumNetwork.avalanche,
        wrappedAddress: '',
        supportSwap: true,
        usesBitquery: false,
        supportMagic: true,
        supportPageExplorer: true,
        coingeckoId: 'avalanche-2',
        isEvm: true,
    },
    [NetworkSlugs.fantom]: {
        name: 'Fantom',
        symbol: 'FTM',
        chainId: ChainId.Fantom,
        networkImage: '/images/networks/fantom.svg',
        coinName: 'Fantom',
        coinImage: '/images/networks/fantom.svg',
        coinSymbol: 'FTM',
        decimals: 18,
        rpcURL: 'https://rpc.ftm.tools/',
        explorerURL: 'https://ftmscan.com/',
        bitqueryNetworkId: EthereumNetwork.fantom,
        wrappedAddress: '',
        supportSwap: true,
        usesBitquery: false,
        supportMagic: true,
        supportPageExplorer: true,
        coingeckoId: 'fantom',
        isEvm: true,
    },
    [NetworkSlugs.okc]: {
        name: 'OKC Mainnet',
        symbol: 'OKT',
        chainId: ChainId.OKC,
        networkImage: '/images/networks/okc.svg',
        coinName: 'OKT',
        coinImage: '/images/networks/okc.svg',
        coinSymbol: 'OKT',
        decimals: 18,
        rpcURL: 'https://exchainrpc.okex.org',
        explorerURL: 'https://www.oklink.com/oec/',
        bitqueryNetworkId: '',
        wrappedAddress: '',
        supportSwap: false,
        usesBitquery: false,
        supportMagic: false,
        supportPageExplorer: false,
        coingeckoId: 'oec-token',
        isEvm: true,
    }



} 