export default interface Events{
  TRANSAK_WIDGET_INITIALISED: string;
  TRANSAK_WIDGET_OPEN: string;
  TRANSAK_WIDGET_CLOSE_REQUEST: string;
  TRANSAK_WIDGET_CLOSE: string;
  TRANSAK_ORDER_CREATED: string;
  TRANSAK_ORDER_CANCELLED: string;
  TRANSAK_ORDER_FAILED: string;
  TRANSAK_ORDER_SUCCESSFUL: string;
}