interface ENVIRONMENT_TYPE {
  FRONTEND: string;
  BACKEND: string;
  NAME: string;
}

export interface ENVIRONMENT {
  STAGING: ENVIRONMENT_TYPE;
  LOCAL_DEVELOPMENT: ENVIRONMENT_TYPE;
  DEVELOPMENT: ENVIRONMENT_TYPE;
  PRODUCTION: ENVIRONMENT_TYPE;
}

export interface STATUS{
  INIT: string;
  TRANSAK_INITIALISED: string;
}
